#!/bin/sh
#
# @name Generic S500 Quadrotor SITL, based on Real Hardware Config
#
# @type Quadrotor X
#

. ${R}etc/init.d/rc.mc_defaults

################################################################################
# Generic
################################################################################

param set-default CBRK_IO_SAFETY 22027
param set-default CBRK_SUPPLY_CHK 894281
param set-default COM_CPU_MAX -1
param set-default COM_OF_LOSS_T 2.5

################################################################################
# Airframe
################################################################################

param set-default SYS_AUTOSTART 22000
param set-default MAV_TYPE 2
param set-default SENS_BOARD_ROT 0

param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 4
param set-default CA_ROTOR0_CT	6.50
param set-default CA_ROTOR0_KM	0.05
param set-default CA_ROTOR0_PX	0.17
param set-default CA_ROTOR0_PY	0.17

param set-default CA_ROTOR1_CT	6.50
param set-default CA_ROTOR1_KM	0.05
param set-default CA_ROTOR1_PX	-0.17
param set-default CA_ROTOR1_PY	-0.17

param set-default CA_ROTOR2_CT	6.50
param set-default CA_ROTOR2_KM	-0.05
param set-default CA_ROTOR2_PX	0.17
param set-default CA_ROTOR2_PY	-0.17

param set-default CA_ROTOR3_CT	6.50
param set-default CA_ROTOR3_KM	-0.05
param set-default CA_ROTOR3_PX	-0.17
param set-default CA_ROTOR3_PY	0.17

param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104


################################################################################
# Battery
################################################################################

param set-default BAT1_N_CELLS 4
param set-default BAT1_R_INTERNAL 0.008
param set-default BAT1_CAPACITY	3300

param set-default BAT1_V_CHARGED 4.15 # New Cells have 4.2V
param set-default BAT1_V_EMPTY 3.50 # Should be > 3.30V
param set-default MC_BAT_SCALE_EN 1

param set-default BAT_LOW_THR 0.15
param set-default BAT_CRIT_THR 0.10
param set-default BAT_EMERGEN_THR 0.05

################################################################################
# Control
################################################################################

param set-default THR_MDL_FAC 0.73
param set-default MPC_THR_HOVER	0.3

param set-default MPC_THR_MAX 0.75
param set-default MPC_THR_MIN 0.

################################################################################
# EKF2
################################################################################

param set-default EKF2_MULTI_IMU 0
param set-default SENS_IMU_MODE 1 # We assume the IMU is already combined into primary
